services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - .env
